-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 12:18:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wyporzyczalnia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wyporzyczalnia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wyporzyczalnia` DEFAULT CHARACTER SET utf8 ;
USE `wyporzyczalnia` ;

-- -----------------------------------------------------
-- Table `wyporzyczalnia`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyporzyczalnia`.`Users` (
  `id` INT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_password` VARCHAR(45) NULL,
  `user_login` VARCHAR(45) NULL,
  `Administration` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyporzyczalnia`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyporzyczalnia`.`Movie` (
  `id` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `direction` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyporzyczalnia`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyporzyczalnia`.`orders` (
  `id` INT NOT NULL,
  `order_status` VARCHAR(45) NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyporzyczalnia`.`orders_has_Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyporzyczalnia`.`orders_has_Movie` (
  `orders_id` INT NOT NULL,
  `orders_Users_id` INT NOT NULL,
  `Movie_id` INT NOT NULL,
  `Movie_Users_id` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `orders_Users_id`, `Movie_id`, `Movie_Users_id`),
  INDEX `fk_orders_has_Movie_Movie1_idx` (`Movie_id` ASC, `Movie_Users_id` ASC) ,
  INDEX `fk_orders_has_Movie_orders1_idx` (`orders_id` ASC, `orders_Users_id` ASC) ,
  CONSTRAINT `fk_orders_has_Movie_orders1`
    FOREIGN KEY (`orders_id` , `orders_Users_id`)
    REFERENCES `wyporzyczalnia`.`orders` (`id` , `Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_Movie_Movie1`
    FOREIGN KEY (`Movie_id`)
    REFERENCES `wyporzyczalnia`.`Movie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wyporzyczalnia`.`Users_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wyporzyczalnia`.`Users_has_orders` (
  `Users_id` INT NOT NULL,
  `orders_id` INT NOT NULL,
  `orders_Users_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `orders_id`, `orders_Users_id`),
  INDEX `fk_Users_has_orders_orders1_idx` (`orders_id` ASC, `orders_Users_id` ASC) ,
  INDEX `fk_Users_has_orders_Users1_idx` (`Users_id` ASC) ,
  CONSTRAINT `fk_Users_has_orders_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `wyporzyczalnia`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_orders_orders1`
    FOREIGN KEY (`orders_id` , `orders_Users_id`)
    REFERENCES `wyporzyczalnia`.`orders` (`id` , `Users_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
